name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js to install dependencies (if using a static site generator)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies if a package.json file exists (optional step)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      # Build the website (if applicable)
      - name: Build website
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Set to your build output directory (e.g., ./dist for static site generators)
